### ISSUE TITLE
More Level 5 Test Cases

### ISSUE THREAD

**Issue by RussellDash332** [nus-cs2030/2122-s1#170]
# Summary
Basically more test cases for you to debug Level 5. If you still anyhow don't know how the simulator works, go to #115.

## Description 
These test cases are actually in CodeCrunch. I managed to trigger it to print the inputs so I can debug them on my own hand. 
For the short ones, you can validate the same way as #162. However, for the long ones, I suggest you to do
`java Main5 < inputfile | diff - expectedoutputfile -w`
and it will compare the output of your simulator to the expected output line-by-line like the CodeCrunch diff.

Basically the way is to put the (one and only) input line in a file and the output file given below. Just change `inputfile` and `expectedoutputfile` with the respective names.

## Files:
**2 5 0 10 1000 7.0 1.0 1.0 0.0 0.5**
[5_5.txt](https://github.com/nus-cs2030/2122-s1/files/7459512/5_5.txt)

**2 0 2 1 5 9.0 1.0 1.0 0.0 0.0**
[5_6.txt](https://github.com/nus-cs2030/2122-s1/files/7459515/5_6.txt)

**2 2 2 3 20 12.0 1.0 1.0 0.0 0.7**
[5_7.txt](https://github.com/nus-cs2030/2122-s1/files/7459517/5_7.txt)

**2 3 2 10 1000 7.0 1.0 1.0 0.0 0.5**
[5_8.txt](https://github.com/nus-cs2030/2122-s1/files/7459519/5_8.txt)

**2 3 2 10 1000 7.0 1.0 1.0 1.0 0.5**
Go to #177 (shoutout to @hingen)

**Comment by TanPingZhi** [comment]
Inb4 Profs next update to codecrunch: make the wrong answers invisible

**Comment by yuehernkang** [comment]
Wow. Thanks so much Russell  !  This is very useful for me to debug my project

**Comment by hingen** [comment]
Thanks for the extra test cases.

Just want to note that you might have made an error with the input for 5_7. There should only be 10 inputs but u included 11 inputs. I couldn't figure out what is the correct input though.

**Comment by RussellDash332** [comment]
> Thanks for the extra test cases!
> 
> Just want to note that you might have made an error with the input for 5_7. There should only be 10 inputs but u included 11 inputs. I couldn't figure out what is the correct input though.

Oh right, I had an extra space! Thanks for telling. I fixed it already

**Comment by hingen** [comment]
I uploaded another extra test case in #177, perhaps you could include it here. It uses 1000 customers and was what broke my code haha.

**Comment by RussellDash332** [comment]
> I uploaded another extra test case in #177, perhaps you could include it here. It uses 1000 customers and was what broke my code haha.

That's my 5_8.txt haha

**Comment by hingen** [comment]
> > I uploaded another extra test case in #177, perhaps you could include it here. It uses 1000 customers and was what broke my code haha.
> 
> That's similar to 5_8 but it's different haha

ah, didn't notice the similarities since I was able to pass 5_8 but still failed CodeCrunch. Seems like the only difference is a 100% probability of rest.

**Comment by jeromepui** [comment]
Just finished my project and have another level 5 test case here :)

**2 2 2 3 20 12.0 1.0 1.0 0.0 0.7**
[5_12.txt](https://github.com/nus-cs2030/2122-s1/files/7486437/5_12.txt)

**Comment by RussellDash332** [comment]
> Just finished my project and have another level 5 test case here if anyone needs it to debug :)
> 
> **2 2 2 3 20 12.0 1.0 1.0 0.0 0.7** [5_12.txt](https://github.com/nus-cs2030/2122-s1/files/7486437/5_12.txt)

Ah thanks! It's the same as my 5_7.txt, probably because I didn't name it after CodeCrunch's TC but rather after 5_4 as a public test case.

**Comment by Devvynneo** [comment]
Thanks for 5_6.txt

never really thought of the scenario where numOfServers is 0 and selfCheckout is not 0 hahaha

back to debugging T.T

**Comment by ezeAng** [comment]
Hi guys anyone knows how to solve this test case?? my code passes all test cases up to here where somehow my customer 3 event runs earlier than my serve done event. My event comparator does check if they are same time then run the check of customer id.

2 0 2 1 5 9.0 1.0 1.0 0.0 0.0
0.000 1 arrives
0.000 1 serves by self-check 1
0.035 2 arrives
0.035 2 serves by self-check 2
0.046 3 arrives
0.046 3 waits at self-check 1
0.124 4 arrives
0.124 4 leaves
0.126 5 arrives
0.126 5 leaves
0.313 3 serves by self-check 1
0.313 1 done serving by self-check 1
2.680 2 done serving by self-check 2
3.015 3 done serving by self-check 1

**Comment by hingen** [comment]
> Hi guys anyone knows how to solve this test case?? my code passes all test cases up to here where somehow my customer 3 event runs earlier than my serve done event. My event comparator does check if they are same time then run the check of customer id.
> 
> 2 0 2 1 5 9.0 1.0 1.0 0.0 0.0 0.000 1 arrives 0.000 1 serves by self-check 1 0.035 2 arrives 0.035 2 serves by self-check 2 0.046 3 arrives 0.046 3 waits at self-check 1 0.124 4 arrives 0.124 4 leaves 0.126 5 arrives 0.126 5 leaves 0.313 3 serves by self-check 1 0.313 1 done serving by self-check 1 2.680 2 done serving by self-check 2 3.015 3 done serving by self-check 1

did u account for floating point precision error?

**Comment by jeromepui** [comment]
> > Hi guys anyone knows how to solve this test case?? my code passes all test cases up to here where somehow my customer 3 event runs earlier than my serve done event. My event comparator does check if they are same time then run the check of customer id.
> > 2 0 2 1 5 9.0 1.0 1.0 0.0 0.0 0.000 1 arrives 0.000 1 serves by self-check 1 0.035 2 arrives 0.035 2 serves by self-check 2 0.046 3 arrives 0.046 3 waits at self-check 1 0.124 4 arrives 0.124 4 leaves 0.126 5 arrives 0.126 5 leaves 0.313 3 serves by self-check 1 0.313 1 done serving by self-check 1 2.680 2 done serving by self-check 2 3.015 3 done serving by self-check 1
> 
> did u account for floating point precision error?

There is actually no need to account for float precision error. I did not check for it at all in my EventComparator. All you need to do is check if event1 is earlier than event2, then return it first and vice versa. Otherwise, the event with the smaller customer ID comes first. I think the possible precision error comes from using =. Just use < or >.

**Comment by hingen** [comment]
> > > Hi guys anyone knows how to solve this test case?? my code passes all test cases up to here where somehow my customer 3 event runs earlier than my serve done event. My event comparator does check if they are same time then run the check of customer id.
> > > 2 0 2 1 5 9.0 1.0 1.0 0.0 0.0 0.000 1 arrives 0.000 1 serves by self-check 1 0.035 2 arrives 0.035 2 serves by self-check 2 0.046 3 arrives 0.046 3 waits at self-check 1 0.124 4 arrives 0.124 4 leaves 0.126 5 arrives 0.126 5 leaves 0.313 3 serves by self-check 1 0.313 1 done serving by self-check 1 2.680 2 done serving by self-check 2 3.015 3 done serving by self-check 1
> > 
> > 
> > did u account for floating point precision error?
> 
> There is actually no need to account for float precision error. I did not check for it at all in my EventComparator. All you need to do is check if event1 is earlier than event2, then return it first and vice versa. Otherwise, the event with the smaller customer ID comes first. I think the possible precision error comes from using =. Just use < or >.

But if 2 events occur at the same time, the event with the customer ID should be return first. To check if 2 events occur at the same time, precision error should be taken into account. I will admit that there are exceptions (such as if no arithmetic is done to calculate the time) so ultimately it does come down to how the code is written.

In this case, I think there is a possbility that the time "0.313" of customer 3 is actually less than "0.313" of customer 1 due to precision error. Thus the customer ID checking is not even done since customer 3's event is assumed to take place earlier than customer 1's event even though they take place at the same time.

**Comment by hgimleng** [comment]
> 
> 
> Hi guys anyone knows how to solve this test case?? my code passes all test cases up to here where somehow my customer 3 event runs earlier than my serve done event. My event comparator does check if they are same time then run the check of customer id.
> 
> 2 0 2 1 5 9.0 1.0 1.0 0.0 0.0 0.000 1 arrives 0.000 1 serves by self-check 1 0.035 2 arrives 0.035 2 serves by self-check 2 0.046 3 arrives 0.046 3 waits at self-check 1 0.124 4 arrives 0.124 4 leaves 0.126 5 arrives 0.126 5 leaves 0.313 3 serves by self-check 1 0.313 1 done serving by self-check 1 2.680 2 done serving by self-check 2 3.015 3 done serving by self-check 1

Does your comparator perform any comparison between event states too? If so that may be causing the issue.

**Comment by Hongyi6328** [comment]
level 5-10
2 0 2 1 5 9.0 1.0 1.0 0.0 0.0

**Comment by lelerer** [comment]
Do you mind sharing how you got all these private test cases?

**Comment by RussellDash332** [comment]
To those wondering how we all got these private test cases, I hope [this](https://github.com/nus-cs2030/2122-s1/issues/198#issuecomment-971741923) answers.

**Comment by francisyzy** [comment]
Level 5_15
`2 2 2 3 20 12.0 1.0 0.5 1.0 0.7`
